create schema securex;
use securex;
select * from book;
drop table users;
create table users(username varchar(50) not null, password varchar(50) not null, enabled boolean not null default true, primary key(username));
create table authorities ( username varchar(50) not null, authority varchar(50) not null, constraint fk_authorities_users foreign key (username) references users (username));
create unique index ix_auth_username on authorities (username, authority);
insert into users (username,password)values ('Bob','password1');
insert into users(username,password) values ('Betty','password2');
insert into authorities (username, authority) values ('Bob', 'ADMIN');
insert into authorities (username, authority) values ('Betty', 'ADMIN');